### ISSUE TITLE
Can't get this to work at all

### ISSUE THREAD

**Issue by L5eoneill** [uiureo/react-overflow-tooltip#1]
`return (
      <div>
        <OverflowTooltip title={name}>
          <div>{nameContent}</div>
        </OverflowTooltip>
      </div>
    );`

Should show up on hover of some overflowing content, right? How do you use this darned thing? My nameContent shows up, but no tooltip

**Comment by uiur** [comment]
Hey, I used this module for a project at work. And I did just in a similar way. 
If you give me more information such as screenshots, maybe I can help you.

**Comment by L5eoneill** [comment]
Found the problem. We're using ES6:
`import {OverflowTooltip} from 'react-overflow-tooltip';`

That's wrong. Instead:
`import OverflowTooltip from 'react-overflow-tooltip';`
